test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
  script:
    - cd src
    - docker-compose -f docker-compose.ci.yml build
    - docker-compose -f docker-compose.ci.yml run harugakita ./run_tests_ci.sh

