FROM microsoft/dotnet:2.2aspnetcore-runtime-alpine as base
WORKDIR /app
EXPOSE 42317
EXPOSE 44302

FROM microsoft/dotnet:2.2-sdk-alpine AS build
WORKDIR /src
COPY HaruGaKita.Test/HaruGaKita.Test.csproj HaruGaKita.Test/
RUN dotnet restore HaruGaKita.Test/HaruGaKita.Test.csproj
COPY . .
WORKDIR /src/HaruGaKita.Test
RUN dotnet build HaruGaKita.Test.csproj -c Release -o /app
WORKDIR /src