FROM microsoft/dotnet:2.1-aspnetcore-runtime-alpine as base
WORKDIR /app
EXPOSE 42317
EXPOSE 44302

FROM microsoft/dotnet:2.1-sdk-alpine AS build
WORKDIR /src
COPY . .
WORKDIR /src/HaruGaKita
RUN dotnet restore
