version: '3.4'
volumes:
  haru-ga-kita-postgresql:
services:
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: harugakita
      password: password
    volumes:
      - haru-ga-kita-postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
  harugakita:
    command: dotnet watch run
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/src
    links:
      - postgres
    ports:
      - 5000:5000
