version: '3.4'
volumes:
  haru-ga-kita-postgresql:
  application-build-files:
  common-build-files:
  domain-build-files:
  persistence-build-files:
  test-build-files:
  webapi-build-files:
services:
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: harugakita
      password: password
    volumes:
      - haru-ga-kita-postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432